export const STOCK_REQUEST_CONSTANTS = {
  PRIORITY_LEVELS: [
    {
      id: 'low',
      label: 'Low',
      description: 'Routine restocking for non-essential items',
      icon: 'arrow-down-outline',
      activeColor: '#DBEAFE',
      activeTextColor: '#1E40AF',
      activeBorderColor: '#3B82F6',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
    {
      id: 'normal',
      label: 'Normal',
      description: 'Standard priority for regular inventory needs',
      icon: 'time-outline',
      activeColor: '#D1FAE5',
      activeTextColor: '#065F46',
      activeBorderColor: '#22C55E',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
    {
      id: 'high',
      label: 'High',
      description: 'Important items needed within 2-3 days',
      icon: 'warning-outline',
      activeColor: '#FEF3C7',
      activeTextColor: '#92400E',
      activeBorderColor: '#F59E0B',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
    {
      id: 'urgent',
      label: 'Urgent',
      description: 'Critical items needed within 24 hours',
      icon: 'flash-outline',
      activeColor: '#FEE2E2',
      activeTextColor: '#B91C1C',
      activeBorderColor: '#EF4444',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
    {
      id: 'critical',
      label: 'Critical',
      description: 'Emergency restocking - out of stock items',
      icon: 'flame-outline',
      activeColor: '#FFEDD5',
      activeTextColor: '#9A3412',
      activeBorderColor: '#F97316',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
  ],

  DELIVERY_OPTIONS: [
    {
      id: 'asap',
      label: 'ASAP (1-2 hours)',
      description: 'Highest priority delivery for emergency needs',
      icon: 'flash-outline',
      activeColor: '#DBEAFE',
      activeTextColor: '#1E40AF',
      activeBorderColor: '#3B82F6',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
    {
      id: 'same_day',
      label: 'Same Day',
      description: 'Delivered today by closing time (6 PM)',
      icon: 'time-outline',
      activeColor: '#F3F4F6',
      activeTextColor: '#6B7280',
      activeBorderColor: '#E5E7EB',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
    {
      id: 'tomorrow',
      label: 'Tomorrow',
      description: 'Next business day delivery by 5 PM',
      icon: 'calendar-outline',
      activeColor: '#F3F4F6',
      activeTextColor: '#6B7280',
      activeBorderColor: '#E5E7EB',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
    {
      id: 'this_week',
      label: 'This Week',
      description: 'Delivery within 3-5 business days',
      icon: 'calendar-outline',
      activeColor: '#F3F4F6',
      activeTextColor: '#6B7280',
      activeBorderColor: '#E5E7EB',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
    {
      id: 'next_week',
      label: 'Next Week',
      description: 'Scheduled for next week (Monday-Friday)',
      icon: 'calendar-outline',
      activeColor: '#F3F4F6',
      activeTextColor: '#6B7280',
      activeBorderColor: '#E5E7EB',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
  ],

  AI_RECOMMENDATIONS: [
    {
      id: '1',
      name: 'Chocolate Cookies',
      description: 'Popular snack item with consistent demand',
      reason: 'Based on your ordering pattern from last month - sales increased 25%',
      price: '$3.99/pack',
      supplier: 'Sweet Treats Bakery',
      icon: 'cookie-outline',
      iconColor: '#EA580C',
      iconBgColor: '#FFEDD5',
      category: 'Snacks',
      currentStock: 3,
      reorderLevel: 10,
      lastOrdered: '2024-11-15',
    },
    {
      id: '2',
      name: 'Mineral Water',
      description: 'Essential beverage with steady consumption',
      reason: 'Current inventory level (5 units) is below minimum threshold (10)',
      price: '$1.25/bottle',
      supplier: 'Aquafina Distributors',
      icon: 'water-outline',
      iconColor: '#22C55E',
      iconBgColor: '#D1FAE5',
      category: 'Beverages',
      currentStock: 5,
      reorderLevel: 10,
      lastOrdered: '2024-11-28',
    },
    {
      id: '3',
      name: 'Coffee Beans',
      description: 'Premium product with high profit margin',
      reason: 'Sales have increased by 40% this week compared to last week',
      price: '$12.99/kg',
      supplier: 'Premium Coffee Roasters',
      icon: 'cafe-outline',
      iconColor: '#92400E',
      iconBgColor: '#FEF3C7',
      category: 'Beverages',
      currentStock: 2,
      reorderLevel: 5,
      lastOrdered: '2024-11-20',
    },
    {
      id: '4',
      name: 'Energy Bars',
      description: 'Health-conscious snack with growing popularity',
      reason: 'Seasonal demand spike detected - approaching fitness season',
      price: '$2.49/bar',
      supplier: 'Healthy Options Ltd.',
      icon: 'fitness-outline',
      iconColor: '#8B5CF6',
      iconBgColor: '#EDE9FE',
      category: 'Health Foods',
      currentStock: 4,
      reorderLevel: 15,
      lastOrdered: '2024-11-10',
    },
  ],

  SEARCHABLE_ITEMS: [
    {
      id: '1',
      name: 'Fresh Apples',
      category: 'Fruits & Vegetables',
      description: 'Crisp and juicy red apples, perfect for snacking',
      price: '$2.99/kg',
      supplier: 'Local Farms Co.',
      icon: 'apple-outline',
      iconColor: '#EF4444',
      iconBgColor: '#FEE2E2',
      currentQuantity: 5,
      sku: 'FRU-APP-001',
      brand: 'Local Farms',
      shelfLife: '7 days',
    },
    {
      id: '2',
      name: 'White Bread',
      category: 'Bakery Items',
      description: 'Freshly baked white bread, soft and fluffy',
      price: '$3.49/loaf',
      supplier: 'Sunrise Bakery',
      icon: 'restaurant-outline',
      iconColor: '#EAB308',
      iconBgColor: '#FEF3C7',
      currentQuantity: 12,
      sku: 'BAK-WHT-002',
      brand: 'Sunrise',
      shelfLife: '3 days',
    },
    {
      id: '3',
      name: 'Whole Milk',
      category: 'Dairy Products',
      description: '1L fresh whole milk, rich in calcium and vitamins',
      price: '$4.25/L',
      supplier: 'Dairy Fresh Ltd.',
      icon: 'wine-outline',
      iconColor: '#3B82F6',
      iconBgColor: '#DBEAFE',
      currentQuantity: 8,
      sku: 'DRY-MLK-003',
      brand: 'Dairy Fresh',
      shelfLife: '5 days',
    },
    {
      id: '4',
      name: 'Chicken Breast',
      category: 'Meat & Poultry',
      description: 'Boneless skinless chicken breast, premium quality',
      price: '$8.99/kg',
      supplier: 'Premium Meats Inc.',
      icon: 'fish-outline',
      iconColor: '#F97316',
      iconBgColor: '#FFEDD5',
      currentQuantity: 3,
      sku: 'MT-PUL-004',
      brand: 'Premium Meats',
      shelfLife: '2 days',
    },
    {
      id: '5',
      name: 'Orange Juice',
      category: 'Beverages',
      description: '100% pure orange juice, no added sugar',
      price: '$3.75/L',
      supplier: 'Citrus Delight Co.',
      icon: 'wine-outline',
      iconColor: '#F59E0B',
      iconBgColor: '#FEF3C7',
      currentQuantity: 6,
      sku: 'BEV-OJU-005',
      brand: 'Citrus Delight',
      shelfLife: '10 days',
    },
    {
      id: '6',
      name: 'Banana Chips',
      category: 'Snacks',
      description: 'Crunchy banana chips, lightly salted',
      price: '$4.99/bag',
      supplier: 'Tropical Snacks Ltd.',
      icon: 'leaf-outline',
      iconColor: '#22C55E',
      iconBgColor: '#D1FAE5',
      currentQuantity: 9,
      sku: 'SNK-BNC-006',
      brand: 'Tropical Snacks',
      shelfLife: '30 days',
    },
  ],

  REQUEST_HISTORY: [
    {
      id: '1234',
      status: 'delivered',
      statusLabel: 'Delivered',
      statusColor: '#22C55E',
      statusBgColor: '#D1FAE5',
      date: 'Dec 10, 2024',
      priority: 'high',
      notes: 'Urgent restock for weekend rush - all items delivered on time',
      items: [
        { name: 'Fresh Apples', quantity: 5, price: '$2.99/kg' },
        { name: 'White Bread', quantity: 12, price: '$3.49/loaf' },
        { name: 'Banana Chips', quantity: 8, price: '$4.99/bag' },
        { name: 'Orange Juice', quantity: 6, price: '$3.75/L' },
      ],
      totalAmount: '$124.75',
      deliveryDate: 'Dec 10, 2024',
      supplier: 'Mixed Suppliers',
    },
    {
      id: '1233',
      status: 'dispatched',
      statusLabel: 'Dispatched',
      statusColor: '#3B82F6',
      statusBgColor: '#DBEAFE',
      date: 'Expected delivery: Today',
      priority: 'normal',
      notes: 'Standard weekly order - delivery expected by 4 PM today',
      items: [
        { name: 'Mineral Water', quantity: 24, price: '$1.25/bottle' },
        { name: 'Chocolate Cookies', quantity: 8, price: '$3.99/pack' },
        { name: 'Coffee Beans', quantity: 3, price: '$12.99/kg' },
      ],
      totalAmount: '$89.91',
      deliveryDate: 'Dec 5, 2024',
      supplier: 'Mixed Suppliers',
    },
    {
      id: '1232',
      status: 'approved',
      statusLabel: 'Approved',
      statusColor: '#EAB308',
      statusBgColor: '#FEF3C7',
      date: 'Approved 2 hours ago',
      priority: 'medium',
      notes: 'Special order for upcoming event - approved for processing',
      items: [
        { name: 'Rice Bags', quantity: 3, price: '$15.99/bag' },
        { name: 'Cooking Oil', quantity: 2, price: '$8.49/bottle' },
        { name: 'Spices Set', quantity: 5, price: '$6.99/set' },
      ],
      totalAmount: '$84.90',
      deliveryDate: 'Est. Dec 8, 2024',
      supplier: 'Grocery Wholesale Co.',
    },
    {
      id: '1231',
      status: 'pending',
      statusLabel: 'Pending',
      statusColor: '#6B7280',
      statusBgColor: '#F3F4F6',
      date: 'Submitted 30 minutes ago',
      priority: 'normal',
      notes: 'Regular replenishment order - awaiting approval',
      items: [
        { name: 'Soft Drinks', quantity: 20, price: '$1.99/can' },
        { name: 'Snacks', quantity: 15, price: '$3.49/bag' },
        { name: 'Energy Bars', quantity: 10, price: '$2.49/bar' },
      ],
      totalAmount: '$117.15',
      deliveryDate: 'Est. Dec 7, 2024',
      supplier: 'Beverage Distributors Inc.',
    },
    {
      id: '1230',
      status: 'rejected',
      statusLabel: 'Rejected',
      statusColor: '#EF4444',
      statusBgColor: '#FEE2E2',
      date: 'Rejected yesterday',
      priority: 'low',
      notes: 'Budget exceeded for this quarter - request denied by manager',
      items: [
        { name: 'Premium Wine', quantity: 12, price: '$18.99/bottle' },
        { name: 'Gourmet Cheese', quantity: 8, price: '$12.49/wedge' },
      ],
      totalAmount: '$327.80',
      deliveryDate: 'N/A',
      supplier: 'Fine Foods Importers',
    },
  ],

  TABS: [
    { id: 'new_request', label: 'New Request' },
    { id: 'history', label: 'History' },
  ],
};