export const STOCK_REQUEST_CONSTANTS = {
  PRIORITY_LEVELS: [
    {
      id: 'normal',
      label: 'Normal',
      icon: 'time-outline',
      activeColor: '#D1FAE5',
      activeTextColor: '#065F46',
      activeBorderColor: '#22C55E',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
    {
      id: 'urgent',
      label: 'Urgent',
      icon: 'flash-outline',
      activeColor: '#FEE2E2',
      activeTextColor: '#B91C1C',
      activeBorderColor: '#EF4444',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
    {
      id: 'critical',
      label: 'Critical',
      icon: 'flame-outline',
      activeColor: '#FFEDD5',
      activeTextColor: '#9A3412',
      activeBorderColor: '#F97316',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
  ],

  DELIVERY_OPTIONS: [
    {
      id: 'asap',
      label: 'ASAP',
      icon: 'time-outline',
      activeColor: '#DBEAFE',
      activeTextColor: '#1E40AF',
      activeBorderColor: '#3B82F6',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
    {
      id: 'tomorrow',
      label: 'Tomorrow',
      icon: 'calendar-outline',
      activeColor: '#F3F4F6',
      activeTextColor: '#6B7280',
      activeBorderColor: '#E5E7EB',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
    {
      id: 'this_week',
      label: 'This Week',
      icon: 'calendar-outline',
      activeColor: '#F3F4F6',
      activeTextColor: '#6B7280',
      activeBorderColor: '#E5E7EB',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
    {
      id: 'custom',
      label: 'Custom',
      icon: 'calendar-outline',
      activeColor: '#F3F4F6',
      activeTextColor: '#6B7280',
      activeBorderColor: '#E5E7EB',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
  ],

  AI_RECOMMENDATIONS: [
    {
      id: '1',
      name: 'Chocolate Cookies',
      description: 'Usually ordered weekly',
      icon: 'cookie-outline',
      iconColor: '#EA580C',
      iconBgColor: '#FFEDD5',
      reason: 'Usually ordered weekly',
    },
    {
      id: '2',
      name: 'Mineral Water',
      description: 'Low stock detected',
      icon: 'water-outline',
      iconColor: '#22C55E',
      iconBgColor: '#D1FAE5',
      reason: 'Low stock detected',
    },
  ],

  SEARCHABLE_ITEMS: [
    {
      id: '1',
      name: 'Fresh Apples',
      category: 'Fruits & Vegetables',
      icon: 'apple-outline',
      iconColor: '#EF4444',
      iconBgColor: '#FEE2E2',
      currentQuantity: 5,
    },
    {
      id: '2',
      name: 'White Bread',
      category: 'Bakery Items',
      icon: 'restaurant-outline',
      iconColor: '#EAB308',
      iconBgColor: '#FEF3C7',
      currentQuantity: 12,
    },
  ],

  REQUEST_HISTORY: [
    {
      id: '1234',
      status: 'delivered',
      statusLabel: 'Delivered',
      statusColor: '#22C55E',
      statusBgColor: '#D1FAE5',
      date: 'Dec 10, 2024',
      items: [
        { name: 'Fresh Apples', quantity: 5 },
        { name: 'White Bread', quantity: 12 },
      ],
    },
    {
      id: '1233',
      status: 'dispatched',
      statusLabel: 'Dispatched',
      statusColor: '#3B82F6',
      statusBgColor: '#DBEAFE',
      date: 'Expected delivery: Today',
      items: [
        { name: 'Mineral Water', quantity: 24 },
        { name: 'Chocolate Cookies', quantity: 8 },
      ],
    },
    {
      id: '1232',
      status: 'approved',
      statusLabel: 'Approved',
      statusColor: '#EAB308',
      statusBgColor: '#FEF3C7',
      date: 'Approved 2 hours ago',
      items: [
        { name: 'Rice Bags', quantity: 3 },
        { name: 'Cooking Oil', quantity: 2 },
      ],
    },
    {
      id: '1231',
      status: 'pending',
      statusLabel: 'Pending',
      statusColor: '#6B7280',
      statusBgColor: '#F3F4F6',
      date: 'Submitted 30 minutes ago',
      items: [
        { name: 'Soft Drinks', quantity: 20 },
        { name: 'Snacks', quantity: 15 },
      ],
    },
  ],

  TABS: [
    { id: 'new_request', label: 'New Request' },
    { id: 'history', label: 'History' },
  ],
};
