export const STOCK_REQUEST_CONSTANTS = {
  PRIORITY_LEVELS: [
    {
      id: 'low',
      label: 'Low',
      description: 'Routine restocking',
      icon: 'arrow-down-outline',
      activeColor: '#DBEAFE',
      activeTextColor: '#1E40AF',
      activeBorderColor: '#3B82F6',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
    {
      id: 'normal',
      label: 'Normal',
      description: 'Standard priority items',
      icon: 'time-outline',
      activeColor: '#D1FAE5',
      activeTextColor: '#065F46',
      activeBorderColor: '#22C55E',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
    {
      id: 'high',
      label: 'High',
      description: 'Important items needed soon',
      icon: 'warning-outline',
      activeColor: '#FEF3C7',
      activeTextColor: '#92400E',
      activeBorderColor: '#F59E0B',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
    {
      id: 'urgent',
      label: 'Urgent',
      description: 'Items needed within 24 hours',
      icon: 'flash-outline',
      activeColor: '#FEE2E2',
      activeTextColor: '#B91C1C',
      activeBorderColor: '#EF4444',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
    {
      id: 'critical',
      label: 'Critical',
      description: 'Emergency restocking required',
      icon: 'flame-outline',
      activeColor: '#FFEDD5',
      activeTextColor: '#9A3412',
      activeBorderColor: '#F97316',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
  ],

  DELIVERY_OPTIONS: [
    {
      id: 'asap',
      label: 'ASAP (1-2 hours)',
      description: 'Highest priority delivery',
      icon: 'flash-outline',
      activeColor: '#DBEAFE',
      activeTextColor: '#1E40AF',
      activeBorderColor: '#3B82F6',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
    {
      id: 'same_day',
      label: 'Same Day',
      description: 'Delivered today by closing time',
      icon: 'time-outline',
      activeColor: '#F3F4F6',
      activeTextColor: '#6B7280',
      activeBorderColor: '#E5E7EB',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
    {
      id: 'tomorrow',
      label: 'Tomorrow',
      description: 'Next business day delivery',
      icon: 'calendar-outline',
      activeColor: '#F3F4F6',
      activeTextColor: '#6B7280',
      activeBorderColor: '#E5E7EB',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
    {
      id: 'this_week',
      label: 'This Week',
      description: 'Delivery within 3-5 business days',
      icon: 'calendar-outline',
      activeColor: '#F3F4F6',
      activeTextColor: '#6B7280',
      activeBorderColor: '#E5E7EB',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
    {
      id: 'next_week',
      label: 'Next Week',
      description: 'Scheduled for next week',
      icon: 'calendar-outline',
      activeColor: '#F3F4F6',
      activeTextColor: '#6B7280',
      activeBorderColor: '#E5E7EB',
      inactiveColor: '#F3F4F6',
      inactiveTextColor: '#6B7280',
      inactiveBorderColor: '#E5E7EB',
    },
  ],

  AI_RECOMMENDATIONS: [
    {
      id: '1',
      name: 'Chocolate Cookies',
      description: 'Usually ordered weekly',
      reason: 'Based on your ordering pattern from last month',
      price: '$3.99/pack',
      supplier: 'Sweet Treats Bakery',
      icon: 'cookie-outline',
      iconColor: '#EA580C',
      iconBgColor: '#FFEDD5',
    },
    {
      id: '2',
      name: 'Mineral Water',
      description: 'Low stock detected',
      reason: 'Current inventory level is below minimum threshold',
      price: '$1.25/bottle',
      supplier: 'Aquafina Distributors',
      icon: 'water-outline',
      iconColor: '#22C55E',
      iconBgColor: '#D1FAE5',
    },
    {
      id: '3',
      name: 'Coffee Beans',
      description: 'High demand item',
      reason: 'Sales have increased by 40% this week',
      price: '$12.99/kg',
      supplier: 'Premium Coffee Roasters',
      icon: 'cafe-outline',
      iconColor: '#92400E',
      iconBgColor: '#FEF3C7',
    },
  ],

  SEARCHABLE_ITEMS: [
    {
      id: '1',
      name: 'Fresh Apples',
      category: 'Fruits & Vegetables',
      description: 'Crisp and juicy red apples, perfect for snacking',
      price: '$2.99/kg',
      supplier: 'Local Farms Co.',
      icon: 'apple-outline',
      iconColor: '#EF4444',
      iconBgColor: '#FEE2E2',
      currentQuantity: 5,
    },
    {
      id: '2',
      name: 'White Bread',
      category: 'Bakery Items',
      description: 'Freshly baked white bread, soft and fluffy',
      price: '$3.49/loaf',
      supplier: 'Sunrise Bakery',
      icon: 'restaurant-outline',
      iconColor: '#EAB308',
      iconBgColor: '#FEF3C7',
      currentQuantity: 12,
    },
    {
      id: '3',
      name: 'Whole Milk',
      category: 'Dairy Products',
      description: '1L fresh whole milk, rich in calcium and vitamins',
      price: '$4.25/L',
      supplier: 'Dairy Fresh Ltd.',
      icon: 'wine-outline',
      iconColor: '#3B82F6',
      iconBgColor: '#DBEAFE',
      currentQuantity: 8,
    },
    {
      id: '4',
      name: 'Chicken Breast',
      category: 'Meat & Poultry',
      description: 'Boneless skinless chicken breast, premium quality',
      price: '$8.99/kg',
      supplier: 'Premium Meats Inc.',
      icon: 'fish-outline',
      iconColor: '#F97316',
      iconBgColor: '#FFEDD5',
      currentQuantity: 3,
    },
  ],

  REQUEST_HISTORY: [
    {
      id: '1234',
      status: 'delivered',
      statusLabel: 'Delivered',
      statusColor: '#22C55E',
      statusBgColor: '#D1FAE5',
      date: 'Dec 10, 2024',
      priority: 'high',
      notes: 'Urgent restock for weekend rush',
      items: [
        { name: 'Fresh Apples', quantity: 5 },
        { name: 'White Bread', quantity: 12 },
        { name: 'Banana Chips', quantity: 8 },
        { name: 'Orange Juice', quantity: 6 },
      ],
    },
    {
      id: '1233',
      status: 'dispatched',
      statusLabel: 'Dispatched',
      statusColor: '#3B82F6',
      statusBgColor: '#DBEAFE',
      date: 'Expected delivery: Today',
      priority: 'normal',
      notes: 'Standard weekly order',
      items: [
        { name: 'Mineral Water', quantity: 24 },
        { name: 'Chocolate Cookies', quantity: 8 },
        { name: 'Coffee Beans', quantity: 3 },
      ],
    },
    {
      id: '1232',
      status: 'approved',
      statusLabel: 'Approved',
      statusColor: '#EAB308',
      statusBgColor: '#FEF3C7',
      date: 'Approved 2 hours ago',
      priority: 'medium',
      notes: 'Special order for upcoming event',
      items: [
        { name: 'Rice Bags', quantity: 3 },
        { name: 'Cooking Oil', quantity: 2 },
        { name: 'Spices Set', quantity: 5 },
      ],
    },
    {
      id: '1231',
      status: 'pending',
      statusLabel: 'Pending',
      statusColor: '#6B7280',
      statusBgColor: '#F3F4F6',
      date: 'Submitted 30 minutes ago',
      priority: 'normal',
      notes: 'Regular replenishment order',
      items: [
        { name: 'Soft Drinks', quantity: 20 },
        { name: 'Snacks', quantity: 15 },
        { name: 'Energy Bars', quantity: 10 },
      ],
    },
    {
      id: '1230',
      status: 'rejected',
      statusLabel: 'Rejected',
      statusColor: '#EF4444',
      statusBgColor: '#FEE2E2',
      date: 'Rejected yesterday',
      priority: 'low',
      notes: 'Budget exceeded for this quarter',
      items: [
        { name: 'Premium Wine', quantity: 12 },
        { name: 'Gourmet Cheese', quantity: 8 },
      ],
    },
  ],

  TABS: [
    { id: 'new_request', label: 'New Request' },
    { id: 'history', label: 'History' },
  ],
};
