apiVersion: v1
kind: Service
metadata:
  name: ai-ml-service
  namespace: cscm
  labels:
    app: ai-ml
    component: ml-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: ai-ml
    component: ml-service