export const SHIPMENT_CONSTANTS = {
  FILTER_OPTIONS: [
    { id: 'active', label: 'Active', count: 4, activeColor: '#2563EB', activeTextColor: '#FFFFFF', inactiveColor: '#F3F4F6', inactiveTextColor: '#6B7280' },
    { id: 'delivered', label: 'Delivered', count: 12, activeColor: '#10B981', activeTextColor: '#FFFFFF', inactiveColor: '#F3F4F6', inactiveTextColor: '#6B7280' },
    { id: 'delayed', label: 'Delayed', count: 2, activeColor: '#F59E0B', activeTextColor: '#FFFFFF', inactiveColor: '#F3F4F6', inactiveTextColor: '#6B7280' },
    { id: 'all', label: 'All Shipments', count: 18, activeColor: '#8B5CF6', activeTextColor: '#FFFFFF', inactiveColor: '#F3F4F6', inactiveTextColor: '#6B7280' },
  ],

  SHIPMENT_STATUS: {
    IN_TRANSIT: { label: 'In Transit', bgColor: '#DBEAFE', textColor: '#1E40AF', borderColor: '#3B82F6' },
    ARRIVING_SOON: { label: 'Arriving Soon', bgColor: '#D1FAE5', textColor: '#065F46', borderColor: '#10B981' },
    DELAYED: { label: 'Delayed', bgColor: '#FFEDD5', textColor: '#9A3412', borderColor: '#F59E0B' },
    OUT_FOR_DELIVERY: { label: 'Out for Delivery', bgColor: '#F3E8FF', textColor: '#7C3AED', borderColor: '#A855F7' },
    DELIVERED: { label: 'Delivered', bgColor: '#D1FAE5', textColor: '#065F46', borderColor: '#10B981' },
  },

  SAMPLE_SHIPMENTS: [
    {
      id: 'SH-2024-001',
      title: 'Electronics & Components',
      description: 'High-value electronic components for manufacturing',
      status: 'in_transit',
      progress: 75,
      eta: 'Today, 3:30 PM',
      transporter: 'FedEx Express',
      distance: '2.5 km away',
      icon: 'location-dot',
      iconColor: '#3B82F6',
      actionText: 'View Details',
      actionColor: '#3B82F6',
      orderValue: '$2,450.00',
      items: 42,
      weight: '12.5 kg',
      dimensions: '30x20x15 cm',
    },
    {
      id: 'SH-2024-002',
      title: 'Raw Materials',
      description: 'Industrial raw materials for production',
      status: 'arriving_soon',
      progress: 95,
      eta: 'Today, 1:15 PM',
      transporter: 'DHL Logistics',
      distance: '0.8 km away',
      icon: 'location-dot',
      iconColor: '#10B981',
      actionText: 'Confirm Delivery',
      actionColor: '#10B981',
      orderValue: '$1,200.00',
      items: 28,
      weight: '8.2 kg',
      dimensions: '25x15x10 cm',
    },
    {
      id: 'SH-2024-003',
      title: 'Office Supplies',
      description: 'General office supplies and stationery',
      status: 'delayed',
      progress: 60,
      eta: 'Tomorrow, 10:00 AM',
      transporter: 'UPS Ground',
      distance: 'Weather delay',
      icon: 'triangle-exclamation',
      iconColor: '#F59E0B',
      actionText: 'View Details',
      actionColor: '#3B82F6',
      orderValue: '$340.50',
      items: 15,
      weight: '3.1 kg',
      dimensions: '20x12x8 cm',
    },
    {
      id: 'SH-2024-004',
      title: 'Packaging Materials',
      description: 'Specialized packaging and protective materials',
      status: 'out_for_delivery',
      progress: 90,
      eta: 'Today, 2:45 PM',
      transporter: 'Local Courier',
      distance: 'Driver: John D.',
      icon: 'truck',
      iconColor: '#A855F7',
      actionText: 'Track Live',
      actionColor: '#3B82F6',
      orderValue: '$780.75',
      items: 36,
      weight: '15.8 kg',
      dimensions: '40x30x25 cm',
    },
    {
      id: 'SH-2024-005',
      title: 'Safety Equipment',
      description: 'Personal protective equipment and safety gear',
      status: 'delivered',
      progress: 100,
      eta: 'Delivered yesterday',
      transporter: 'FedEx Ground',
      distance: 'Delivered',
      icon: 'shield-alt',
      iconColor: '#10B981',
      actionText: 'View Receipt',
      actionColor: '#10B981',
      orderValue: '$1,120.00',
      items: 22,
      weight: '6.4 kg',
      dimensions: '28x18x12 cm',
    },
  ],

  QUICK_ACTIONS: [
    {
      id: 'scan-barcode',
      title: 'Scan Barcode',
      icon: 'qr-code',
      color: '#3B82F6',
    },
    {
      id: 'photo-upload',
      title: 'Photo Upload',
      icon: 'camera',
      color: '#3B82F6',
    },
    {
      id: 'add-note',
      title: 'Add Note',
      icon: 'note-sticky',
      color: '#8B5CF6',
    },
    {
      id: 'contact-driver',
      title: 'Contact Driver',
      icon: 'phone',
      color: '#10B981',
    },
  ],

  RECENT_DELIVERIES: [
    {
      id: 'SH-2023-998',
      title: 'Electronics & Accessories',
      deliveredAt: 'Delivered yesterday at 2:30 PM',
      itemCount: '24 items',
      status: 'delivered',
      orderValue: '$2,150.00',
      transporter: 'FedEx Express',
    },
    {
      id: 'SH-2023-997',
      title: 'Home & Garden',
      deliveredAt: 'Delivered 2 days ago at 11:15 AM',
      itemCount: '15 items',
      status: 'delivered',
      orderValue: '$890.50',
      transporter: 'DHL Logistics',
    },
    {
      id: 'SH-2023-996',
      title: 'Automotive Parts',
      deliveredAt: 'Delivered 3 days ago at 4:45 PM',
      itemCount: '32 items',
      status: 'delivered',
      orderValue: '$3,200.75',
      transporter: 'UPS Ground',
    },
    {
      id: 'SH-2023-995',
      title: 'Clothing & Apparel',
      deliveredAt: 'Delivered 4 days ago at 9:30 AM',
      itemCount: '48 items',
      status: 'delivered',
      orderValue: '$1,450.25',
      transporter: 'Local Courier',
    },
  ],
};