export const INVENTORY_CONSTANTS = {
  FILTER_OPTIONS: [
    { id: 'all', label: 'All Items', active: true },
    { id: 'low-stock', label: 'Low Stock', active: false },
    { id: 'electronics', label: 'Electronics', active: false },
    { id: 'clothing', label: 'Clothing', active: false },
    { id: 'audio', label: 'Audio', active: false },
    { id: 'expired', label: 'Expired', active: false },
  ],
  
  STOCK_STATUS: {
    LOW: { color: '#EF4444', bgColor: '#FEE2E2', textColor: '#DC2626', label: 'Low Stock' },
    IN_STOCK: { color: '#22C55E', bgColor: '#D1FAE5', textColor: '#16A34A', label: 'In Stock' },
    EXPIRING: { color: '#F97316', bgColor: '#FED7AA', textColor: '#EA580C', label: 'Expires Soon' },
  },
  
  ITEM_TYPES: {
    ELECTRONICS: 'Electronics',
    CLOTHING: 'Clothing',
    FOOD: 'Food',
    ACCESSORIES: 'Accessories',
  },
  
  STATS_DATA: {
    totalItems: 1247,
    lowStock: 23,
    expiringSoon: 7,
  },
  
  SAMPLE_INVENTORY: [
    {
      id: 1,
      name: 'MacBook Pro 16"',
      sku: 'MBP16-001',
      supplier: 'Apple Inc.',
      quantity: 3,
      status: 'low',
      type: 'Electronics',
      expiryDate: null,
      borderColor: '#EF4444',
      category: 'Computers',
      price: 2499.99,
      cost: 2000.00,
      lastUpdated: '2023-12-01',
      location: 'Aisle 3, Shelf 2',
      description: 'The MacBook Pro 16" features the powerful M2 Pro or M2 Max chip, a stunning Liquid Retina XDR display, and up to 22 hours of battery life.',
      weight: '4.7 lbs',
      dimensions: '14.91 x 10.71 x 0.66 in',
    },
    {
      id: 2,
      name: 'iPhone 15 Pro',
      sku: 'IP15P-128',
      supplier: 'Apple Inc.',
      quantity: 47,
      status: 'in-stock',
      type: 'Electronics',
      expiryDate: null,
      borderColor: null,
      category: 'Mobile Phones',
      price: 999.99,
      cost: 750.00,
      lastUpdated: '2023-11-30',
      location: 'Aisle 1, Shelf 5',
      description: 'iPhone 15 Pro features a titanium design, A17 Pro chip, and a 48MP camera system with 5x Telephoto zoom.',
      weight: '0.68 lbs',
      dimensions: '5.75 x 2.82 x 0.32 in',
    },
    {
      id: 3,
      name: 'Organic Milk 1L',
      sku: 'MLK-ORG-1L',
      supplier: 'Fresh Farms Co.',
      quantity: 24,
      status: 'expiring',
      type: 'Food',
      expiryDate: 'Dec 15',
      borderColor: '#F97316',
      category: 'Dairy',
      price: 4.99,
      cost: 2.50,
      lastUpdated: '2023-12-01',
      location: 'Refrigerator Section 2',
      description: 'Fresh organic milk from grass-fed cows. No antibiotics or hormones. Pasteurized and homogenized.',
      weight: '1.05 kg',
      dimensions: '3.5 x 3.5 x 9.5 in',
    },
    {
      id: 4,
      name: 'Samsung Galaxy S24',
      sku: 'SGS24-256',
      supplier: 'Samsung',
      quantity: 32,
      status: 'in-stock',
      type: 'Electronics',
      expiryDate: null,
      borderColor: null,
      category: 'Mobile Phones',
      price: 899.99,
      cost: 650.00,
      lastUpdated: '2023-11-29',
      location: 'Aisle 1, Shelf 4',
      description: 'Samsung Galaxy S24 features a stunning Dynamic AMOLED display, Snapdragon 8 Gen 3 processor, and advanced camera system.',
      weight: '0.67 lbs',
      dimensions: '5.7 x 2.8 x 0.31 in',
    },
    {
      id: 5,
      name: 'Nike Air Max 270',
      sku: 'NAM270-42',
      supplier: 'Nike Inc.',
      quantity: 18,
      status: 'in-stock',
      type: 'Clothing',
      expiryDate: null,
      borderColor: null,
      category: 'Footwear',
      price: 150.00,
      cost: 90.00,
      lastUpdated: '2023-11-28',
      location: 'Aisle 5, Shelf 1',
      description: 'Nike Air Max 270 features Max Air cushioning in the heel for a smooth, cushioned ride. Lightweight and breathable mesh upper.',
      weight: '1.2 lbs',
      dimensions: '13 x 6 x 5 in',
    },
    {
      id: 6,
      name: 'Organic Eggs (12 count)',
      sku: 'EGG-ORG-12',
      supplier: 'Green Valley Farms',
      quantity: 65,
      status: 'in-stock',
      type: 'Food',
      expiryDate: 'Dec 20',
      borderColor: null,
      category: 'Dairy',
      price: 3.99,
      cost: 2.20,
      lastUpdated: '2023-12-01',
      location: 'Refrigerator Section 1',
      description: 'Free-range organic eggs from pasture-raised hens. Rich in omega-3 fatty acids and vitamins.',
      weight: '0.75 kg',
      dimensions: '4 x 4 x 6 in',
    },
    {
      id: 7,
      name: 'Sony WH-1000XM5 Headphones',
      sku: 'SONY-WH1000XM5',
      supplier: 'Sony Electronics',
      quantity: 12,
      status: 'in-stock',
      type: 'Electronics',
      expiryDate: null,
      borderColor: null,
      category: 'Audio',
      price: 399.99,
      cost: 280.00,
      lastUpdated: '2023-11-25',
      location: 'Aisle 2, Shelf 3',
      description: 'Industry-leading noise canceling headphones with 30-hour battery life and premium sound quality.',
      weight: '0.25 lbs',
      dimensions: '8 x 7 x 3 in',
    },
  ],
  
  SWIPE_ACTIONS: {
    EDIT: { color: '#3B82F6', icon: 'create-outline' },
    ALERT: { color: '#EF4444', icon: 'warning-outline' },
    EXPIRY: { color: '#F97316', icon: 'time-outline' },
  },
};